### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by cameron-elliott** [tightenco/jigsaw-docs-template#36]
Okay, a simple question for you guys, and remember I am faking/fudging my way though with Laravel/php/etc...

If I go to this url: http://jigsaw-docs-staging.tighten.co/docs
I get a **403 Forbidden** message, which is maybe my fault for cutting urls, but I can't
be the only one who does this, right?

What is the best way to make this url:
http://jigsaw-docs-staging.tighten.co/docs 
jump to the homepage, or the first article in the docs folder:
http://jigsaw-docs-staging.tighten.co/docs/getting-started/

Maybe the resulting small tweak would be worthy of a PR so url choppers don't get 404/403s?

Sorry if this is more of a Laravel than Jigsaw question, but I think a small fix could benefit the template.

Cheers,
Cameron

**Comment by mattstauffer** [comment]
@cameron-elliott Interestingly, that's *not* a Laravel issue, because by the time you hit your site, you're seeing HTML served by nginx.

This is our preferred solution:
https://jigsaw.tighten.co/docs/custom-404-page/
